### ISSUE TITLE
Can this only activate 365? Or can all series be activated?

### ISSUE THREAD

**Issue by hewit-hue** [asdcorp/ohook#1]
Can this only activate 365? Or can all series be activated?
I hope the more authors, the better, looking forward to it

**Comment by WindowsAddict** [comment]
Ohook activation method can activate all kinds of Office versions on Windows 8 and higher and their Server equivalent except Office 2010 and Office UWP apps.

**Comment by hewit-hue** [comment]
> Ohook activation method can activate all kinds of Office versions on Windows 8 and higher and their Server equivalent except Office 2010 and Office UWP apps.
That's great, thank you for your answer

**Comment by ShinjoKurumi** [comment]
Readme.md only lists blank keys for O365HomePrem and O365ProPlus.

To activate other Office skus, just find a blocked key that belongs to the SKU you want to use.
The application will be activated with that key and the function of this patch. 

![屏幕截图 2023-09-27 174941](https://github.com/asdcorp/ohook/assets/66598407/0f9de41b-4358-477c-af74-59fe3cfa9258)

**Comment by WindowsAddict** [comment]
> To activate other Office skus, just find a blocked key that belongs to the SKU you want to use. 

You can find the keys here https://massgrave.dev/ohook.html#Supported_Products
